import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
      {/* Footer */}
      <footer className="border-t border-white/10 bg-[#060b12]">
        <div className="mx-auto max-w-7xl px-6 py-12">
          <div className="grid gap-10 md:grid-cols-2 lg:grid-cols-4">
            {/* Brand */}
            <div>
              <p className="inline-flex rounded-full border border-yellow-400/30 bg-yellow-400/10 px-4 py-1 text-sm text-yellow-300">
                Frozen Sherpa Foods
              </p>
              <p className="mt-4 text-sm leading-6 text-white/60">
                Sherpa tradition meets healthy & hearty food. Convenient,
                nutritious, and delicious meals for busy lifestyles.
              </p>
            </div>

            {/* Quick Links */}
            <div>
              <h3 className="text-sm font-semibold text-white">Quick Links</h3>
              <ul className="mt-4 space-y-3 text-sm text-white/60">
                <li>
                  <a href="#menu" className="hover:text-yellow-300">
                    Menu
                  </a>
                </li>
                <li>
                  <a href="#blog" className="hover:text-yellow-300">
                    Blog
                  </a>
                </li>
                <li>
                  <a href="/about" className="hover:text-yellow-300">
                    About Us
                  </a>
                </li>
                <li>
                  <a href="/contact" className="hover:text-yellow-300">
                    Contact
                  </a>
                </li>
              </ul>
            </div>

            {/* Location */}
            <div>
              <h3 className="text-sm font-semibold text-white">Location</h3>
              <p className="mt-4 text-sm leading-6 text-white/60">
                Toronto, Ontario<br />
                Canada
              </p>
            </div>

            {/* Contact */}
            <div>
              <h3 className="text-sm font-semibold text-white">Contact</h3>
              <ul className="mt-4 space-y-3 text-sm text-white/60">
                <li>
                  <a href="mailto:hello@frozensherpafoods.com" className="hover:text-yellow-300">
                    hello@frozensherpafoods.com
                  </a>
                </li>
                {/* Optional: phone if you have one
                <li>
                  <a href="tel:+1234567890" className="hover:text-yellow-300">
                    +1 (234) 567-890
                  </a>
                </li>
                */}
              </ul>
            </div>
          </div>

          {/* Bottom bar */}
          <div className="mt-10 flex flex-col items-center justify-between gap-4 border-t border-white/10 pt-6 text-sm text-white/50 md:flex-row">
            <p>&copy; {new Date().getFullYear()} Frozen Sherpa Foods. All rights reserved.</p>
            <div className="flex gap-4">
              <a href="/privacy" className="hover:text-yellow-300">
                Privacy
              </a>
              <a href="/terms" className="hover:text-yellow-300">
                Terms
              </a>
            </div>
          </div>
        </div>
      </footer>
    </html>
  );
}
